# Cloudflare Pages configuration
name = "blockeddrainsaberdeen-co-uk"
pages_build_output_dir = "dist"
compatibility_date = "2024-12-20"

[[d1_databases]]
binding = "DB"
database_name = "aberdeen-leads"
database_id = "ae69f916-a47e-46ac-a2e7-08a39300473e"
